hotel_homepage:
    path:     /Connected
    defaults: { _controller: HotelBundle:Default:index }
list_hotels:
    path:     /Connected/Listhotels
    defaults: { _controller: HotelBundle:Default:viewHotels}
