hotel_homepage:
    path:     /Connected
    defaults: { _controller: HotelBundle:Default:index }
create_hotel:
    path:     /Connected/Hotel/Create
    defaults: { _controller: "HotelBundle:Default:createHotel" }
list_hotels:
    path:     /Connected/Hotel/List
    defaults: { _controller: HotelBundle:Default:viewHotels}
delete_hotel:
    path:     /Connected/Hotel/{id}/Delete
    defaults: { _controller: "HotelBundle:Default:deleteHotel" }    
edit_hotel:
    path:     /Connected/Hotel/Edit/{id}
    defaults: { _controller: "HotelBundle:Default:editHotel" }


update_hotel:
    path:     /Connected/Hotel/{id}/update
    defaults: { _controller: "HotelBundle:Default:updateHotel" }
    
add_categorie:
    path:     /Connected/Hotel/categorie
    defaults: { _controller: "HotelBundle:Default:addCategorie" }
delete_categorie:
    path:     /Connected/Hotel/delete/categorie
    defaults: { _controller: "HotelBundle:Default:deleteCategorie" }
add_ville:
    path:     /Connected/Hotel/ville
    defaults: { _controller: "HotelBundle:Default:addVille" }  
delete_ville:
    path:     /Connected/Hotel/delete/ville
    defaults: { _controller: "HotelBundle:Default:deleteVille" }
delete_picture:
    path:     /Connected/Hotel/delete/picture
    defaults: { _controller: "HotelBundle:Default:deletePicture" }
add_details_hotel:
    path:     /Connected/Hotel/addDetails
    defaults: { _controller: "HotelBundle:Default:addDetailsHotel" }
get_ville_hotel:
    path:     /Connected/Hotel/getville
    defaults: { _controller: "HotelBundle:Default:getVilleByHotel" }
add_tarif_hotel:
    path:     /Connected/Hotel/addTarif
    defaults: { _controller: "HotelBundle:Tarif:addTarifHotel" }
get_villetarif_hotel:
    path:     /Connected/Hotel/tarif/getville
    defaults: { _controller: "HotelBundle:Tarif:getVilleByHotelTarif" }
add_tarifperiode_hotel:
    path:     /Connected/Hotel/TarifPeriode
    defaults: { _controller: "HotelBundle:Tarif:addTarifPeriodeHotel" }
pre_listtarif_hotel:
    path:     /Connected/Hotel/displayTarifs1
    defaults: { _controller: "HotelBundle:Tarif:preDisplayTarif" }
list_tarif_hotel:
    path:     /Connected/Hotel/list/Tarifs
    defaults: { _controller: "HotelBundle:Tarif:listTarifsHotel" }
edit_tarif:
    path:     /Connected/Hotel/EditTarif/{id}
    defaults: { _controller: "HotelBundle:Tarif:editTarif" }
update_tarif:
    path:     /Connected/Hotel/tarif/{id}/update
    defaults: { _controller: "HotelBundle:Tarif:updateTarifPeriodeHotel" }
delete_tarif:
    path:     /Connected/Hotel/tarif/{id}/Delete
    defaults: { _controller: "HotelBundle:Tarif:deleteTarif" }
    