list_contacts:
    path:     /Connected/Contacts/List
    defaults: { _controller: "CMSBundle:Contact:listContacts" }
delete_contact:
    path:     /Connected/Contacts/{id}/Delete
    defaults: { _controller: "CMSBundle:Contact:deleteContact" }
list_bannieres:
    path:     /Connected/Bannieres/List
    defaults: { _controller: "CMSBundle:Accueil:listBannieres" }
delete_banniere:
    path:     /Connected/Banniere/{id}/Delete
    defaults: { _controller: "CMSBundle:Accueil:deleteBanniere" }
    
