<?php

namespace CMSBundle\Repository;

/**
 * HotelAccRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelAccRepository extends \Doctrine\ORM\EntityRepository
{
}
