<?php

namespace Etourisme\HotelBundle\Repository;

/**
 * DetailsArrangementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailsArrangementRepository extends \Doctrine\ORM\EntityRepository
{
}
