<?php

namespace Etourisme\HotelBundle\Repository;

/**
 * DetailsReductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailsReductionRepository extends \Doctrine\ORM\EntityRepository
{
}
