<?php

namespace Etourisme\HotelBundle\Repository;

/**
 * DetailsHotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailsHotelRepository extends \Doctrine\ORM\EntityRepository
{
}
