<?php

namespace Etourisme\HotelBundle\Repository;

/**
 * DetailsThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailsThemeRepository extends \Doctrine\ORM\EntityRepository
{
}
