<?php

namespace Etourisme\HotelBundle\Repository;

/**
 * DetailsChambreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailsChambreRepository extends \Doctrine\ORM\EntityRepository
{
}
