<?php

namespace Etourisme\HotelBundle\Repository;

/**
 * DetailsHotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailsHotelRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDetailsHotelByTemps($hotel_id,$checkin,$checkout) {
        $qb = $this->createQueryBuilder('j')
                ->where('j.hotel  = :hotel_id and j.tempsd <= :checkin and  j.tempsf >= :checkout')  
                ->setParameter('hotel_id', $hotel_id)
                ->setParameter('checkin', $checkin )
                ->setParameter('checkout', $checkout )
        ;
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
