<?php

namespace Etourisme\HotelBundle\Repository;

/**
 * OccupantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OccupantRepository extends \Doctrine\ORM\EntityRepository
{
}
