<?php

namespace Etourisme\HotelBundle\Repository;

/**
 * ReductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReductionRepository extends \Doctrine\ORM\EntityRepository
{
}
